# Generated by Django 3.2.2 on 2021-05-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20210508_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='progress',
            field=models.FloatField(),
        ),
    ]
